# Generated by Django 4.2.4 on 2023-09-16 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0007_remove_task_category_task_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="lists.category"
            ),
        ),
    ]
