# Generated by Django 4.2.4 on 2023-09-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0009_task_created_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="content",),
        migrations.RemoveField(model_name="task", name="created_at",),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="task",
            name="name",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
    ]
