# Generated by Django 4.2.4 on 2023-09-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0012_alter_task_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
