# Generated by Django 4.2.4 on 2023-09-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0014_alter_category_options_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"ordering": ["category"]},
        ),
    ]
