# Generated by Django 4.2.4 on 2023-09-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0015_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="task", options={"ordering": ["id"]},),
    ]
