# Generated by Django 4.2.4 on 2023-09-20 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0016_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task", options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
