# Generated by Django 4.2.4 on 2023-09-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0018_alter_task_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="task",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
