# Generated by Django 4.2.4 on 2023-09-25 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lists", "0020_remove_category_slug_remove_task_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(name="category", options={"ordering": ["-id"]},),
        migrations.AlterField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
