# Generated by Django 4.2.4 on 2023-09-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0021_alter_category_options_alter_category_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
    ]
