# Generated by Django 4.2.4 on 2023-10-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0023_alter_category_category_alter_category_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100, unique=True),
        ),
    ]
