# Generated by Django 4.2.6 on 2023-10-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0025_alter_category_category_alter_category_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["-id"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Tasks"},
        ),
    ]
