# Generated by Django 4.2.4 on 2023-08-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_profile_city_profile_country_profile_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
