# Generated by Django 4.2.4 on 2023-08-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_profile_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="sex",
            field=models.CharField(
                choices=[("0", "Unisex"), ("1", "Female"), ("2", "Male")],
                default="Unisex",
                max_length=50,
            ),
        ),
    ]
