# Generated by Django 4.2.4 on 2023-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_profile_sex"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="sex",),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male"), ("U", "Unisex")],
                default="Unisex",
                max_length=20,
            ),
        ),
    ]
