# Generated by Django 4.2.4 on 2023-08-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="sex",
            field=models.CharField(
                choices=[("1", "Female"), ("2", "Male")],
                default="Unisex",
                max_length=50,
            ),
        ),
    ]
