# Generated by Django 4.2.4 on 2023-08-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_profile_sex_user_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="profile_pics"
            ),
        ),
    ]
