# Generated by Django 4.2.4 on 2023-08-26 16:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_alter_profile_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="sex", ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("ND", "Not Defined")],
                default="Not Defined",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default='default.jpg',
                upload_to="profile_pics",
            ),
        ),
    ]
