# Generated by Django 4.2.4 on 2023-08-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_remove_user_sex_user_gender_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Not Defined",
                max_length=20,
            ),
        ),
    ]
