# Generated by Django 4.2.4 on 2023-08-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="User", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="", upload_to="profile_pics"),
        ),
    ]
