# Generated by Django 4.2.4 on 2023-08-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_user_first_name_alter_profile_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="image",),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics"),
        ),
    ]
