# Generated by Django 4.2.4 on 2023-08-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_remove_profile_image_user_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="first_name",),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(default="", upload_to="profile_pics"),
        ),
    ]
