# Generated by Django 4.2.4 on 2023-08-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_remove_profile_first_name_alter_user_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="last_name",),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
