# Generated by Django 4.2.4 on 2023-09-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_profile_date_of_birth_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
