# Generated by Django 4.2.4 on 2023-09-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="default.jpg", null=True, upload_to="profile_pics"
            ),
        ),
    ]
