# Generated by Django 4.2.4 on 2023-09-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_alter_user_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="gender",),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Not Defined",
                max_length=20,
            ),
        ),
    ]
