# Generated by Django 4.2.4 on 2023-09-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_alter_profile_gender"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="phone_number",),
    ]
