# Generated by Django 4.2.4 on 2023-10-07 19:19

from django.conf import settings
import django.core.exceptions
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_remove_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True, db_column="profile_city", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(
                blank=True, db_column="profile_country", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.CharField(
                blank=True, db_column="profile_date_of_birth", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(
                blank=True, db_column="profile_first_name", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Not Defined", "Not Defined"),
                    ("Male", "Male"),
                    ("Female", "Female"),
                ],
                db_column="profile_gender",
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(
                blank=True, db_column="profile_last_name", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="province",
            field=models.CharField(
                blank=True, db_column="profile_province", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                db_column="user_profile",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                db_column="user_date_joined", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                db_column="user_email",
                default="",
                max_length=254,
                unique=True,
                validators=[django.core.exceptions.ValidationError],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                db_column="user_image",
                default="default.jpg",
                null=True,
                upload_to="profile_pics",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(db_column="user_is_active", default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(db_column="user_is_staff", default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(db_column="user_is_superuser", default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(db_column="user_is_verified", default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, db_column="user_last_login", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_column="user_username", default="", max_length=50, unique=True
            ),
        ),
    ]
